<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="config" autocomplete="off">
	<ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#common" role="tab" data-toggle="tab"><i class="fa fa-home fa-fw"></i> <?php $this->show('Common'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#dimensions" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Dimensions'); ?></a></li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane fade in active" id="common" role="tabpanel">
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Photos in an album per page'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[photos_per_page]', $config->getPerPageCount(), array('class' => 'form-control', 'min' => '1')); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('How many photos do you want to be shown per album on your site?'); ?></span>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Quality'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[quality]', $config->getQuality(), array('class' => 'form-control', 'min' => '1', 'max' => '100')); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Quality for saved images. 100 - best quality, 50 - medium, 20 or lower - worst'); ?></span>
                </div>
            </div>
		</div>
		<!--/Common-->

		<div class="tab-pane fade" id="dimensions" role="tabpanel">
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Maximal image height"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[max_img_height]', $config->getMaxHeight(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Maximal allowed height for photos on site. 0 - do not take into account'); ?></span>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Maximal image width"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[max_img_width]', $config->getMaxWidth(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Maximal allowed width for photos on site. 0 - do not take into account'); ?></span>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Thumb's height"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[thumb_height]', $config->getHeight(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Desired thumbs height when viewing on site'); ?></span>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Thumb's width"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[thumb_width]', $config->getWidth(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Desired thumbs width when viewing on site'); ?></span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Album's thumb height"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[album_thumb_height]', $config->getAlbumThumbHeight(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Desired album thumbs height when viewing on site'); ?></span>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show("Album's thumb width"); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::number('config[album_thumb_width]', $config->getAlbumThumbWidth(), array('class' => 'form-control', 'readonly' => !$extendedMode)); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                    <span class="help-block"><?php $this->show('Desired album thumbs width when viewing on site'); ?></span>
                </div>
            </div>
		</div>
	</div>

    <div class="actions">
        <button data-button="save" data-url="<?php echo $this->url('Photogallery:Admin:Config@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
        <button data-button="cancel" data-url="<?php echo $this->url('Photogallery:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Cancel'); ?></button>
    </div>
</form>
